CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Currencies" (
    "CurrencyId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(5) NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Symbol" character varying(5) NOT NULL,
    "Flag" character varying(10),
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Currencies" PRIMARY KEY ("CurrencyId")
);

CREATE TABLE "Users" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(150) NOT NULL,
    "PasswordHash" character varying(255) NOT NULL,
    "CurrencyId" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Users_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("CurrencyId") ON DELETE CASCADE
);

CREATE TABLE "Categories" (
    "CategoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "Name" character varying(50) NOT NULL,
    "Icon" character varying(50),
    "Color" character varying(10),
    "IsDefault" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("CategoryId"),
    CONSTRAINT "FK_Categories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId")
);

CREATE TABLE "Wallets" (
    "WalletId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "WalletType" character varying(20) NOT NULL,
    "Balance" numeric(18,2) NOT NULL,
    "CurrencyId" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Wallets" PRIMARY KEY ("WalletId"),
    CONSTRAINT "FK_Wallets_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("CurrencyId") ON DELETE CASCADE,
    CONSTRAINT "FK_Wallets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Budgets" (
    "BudgetId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "MonthYear" character varying(7) NOT NULL,
    "LimitAmount" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Budgets" PRIMARY KEY ("BudgetId"),
    CONSTRAINT "FK_Budgets_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("CategoryId") ON DELETE CASCADE,
    CONSTRAINT "FK_Budgets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Expenses" (
    "ExpenseId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "WalletId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "ExpenseDate" timestamp with time zone NOT NULL,
    "TransactionType" character varying(10) NOT NULL,
    "Description" character varying(250),
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Expenses" PRIMARY KEY ("ExpenseId"),
    CONSTRAINT "FK_Expenses_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("CategoryId") ON DELETE CASCADE,
    CONSTRAINT "FK_Expenses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE,
    CONSTRAINT "FK_Expenses_Wallets_WalletId" FOREIGN KEY ("WalletId") REFERENCES "Wallets" ("WalletId") ON DELETE CASCADE
);

CREATE TABLE "RecurringExpenses" (
    "RecurringId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "WalletId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Description" character varying(250),
    "Type" character varying(20) NOT NULL,
    "Frequency" character varying(10) NOT NULL,
    "PrincipalAmount" numeric(18,2),
    "InterestRate" numeric(5,2),
    "TenureMonths" integer,
    "InstallmentsPaid" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "NextDueDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_RecurringExpenses" PRIMARY KEY ("RecurringId"),
    CONSTRAINT "FK_RecurringExpenses_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("CategoryId") ON DELETE CASCADE,
    CONSTRAINT "FK_RecurringExpenses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE,
    CONSTRAINT "FK_RecurringExpenses_Wallets_WalletId" FOREIGN KEY ("WalletId") REFERENCES "Wallets" ("WalletId") ON DELETE CASCADE
);

CREATE TABLE "WalletTransfers" (
    "TransferId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "FromWalletId" integer NOT NULL,
    "ToWalletId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Note" character varying(250),
    "TransferredAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WalletTransfers" PRIMARY KEY ("TransferId"),
    CONSTRAINT "FK_WalletTransfers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE,
    CONSTRAINT "FK_WalletTransfers_Wallets_FromWalletId" FOREIGN KEY ("FromWalletId") REFERENCES "Wallets" ("WalletId"),
    CONSTRAINT "FK_WalletTransfers_Wallets_ToWalletId" FOREIGN KEY ("ToWalletId") REFERENCES "Wallets" ("WalletId")
);

CREATE INDEX "IX_Budgets_CategoryId" ON "Budgets" ("CategoryId");

CREATE UNIQUE INDEX "IX_Budgets_UserId_CategoryId_MonthYear" ON "Budgets" ("UserId", "CategoryId", "MonthYear");

CREATE INDEX "IX_Budgets_UserId_MonthYear" ON "Budgets" ("UserId", "MonthYear");

CREATE INDEX "IX_Categories_UserId" ON "Categories" ("UserId");

CREATE UNIQUE INDEX "IX_Currencies_Code" ON "Currencies" ("Code");

CREATE INDEX "IX_Expenses_CategoryId" ON "Expenses" ("CategoryId");

CREATE INDEX "IX_Expenses_UserId_ExpenseDate" ON "Expenses" ("UserId", "ExpenseDate" DESC);

CREATE INDEX "IX_Expenses_WalletId" ON "Expenses" ("WalletId");

CREATE INDEX "IX_RecurringExpenses_CategoryId" ON "RecurringExpenses" ("CategoryId");

CREATE INDEX "IX_RecurringExpenses_NextDueDate_IsActive" ON "RecurringExpenses" ("NextDueDate", "IsActive");

CREATE INDEX "IX_RecurringExpenses_UserId" ON "RecurringExpenses" ("UserId");

CREATE INDEX "IX_RecurringExpenses_WalletId" ON "RecurringExpenses" ("WalletId");

CREATE INDEX "IX_Users_CurrencyId" ON "Users" ("CurrencyId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE INDEX "IX_Wallets_CurrencyId" ON "Wallets" ("CurrencyId");

CREATE INDEX "IX_Wallets_UserId" ON "Wallets" ("UserId");

CREATE INDEX "IX_WalletTransfers_FromWalletId" ON "WalletTransfers" ("FromWalletId");

CREATE INDEX "IX_WalletTransfers_ToWalletId" ON "WalletTransfers" ("ToWalletId");

CREATE INDEX "IX_WalletTransfers_UserId" ON "WalletTransfers" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260308174747_InitialPostgres', '9.0.1');

COMMIT;

